version: "3"
services:
  db:
    image: "postgres:9.5"
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    depends_on:
      - db
    ports:
    - "8888:8888"
    volumes:
    - "./notebooks:/home/jovyan/work"
    command: "start-notebook.sh"
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    depends_on:
      - db
    ports:
    - "3000:3000"
    volumes:
    - ".:/app"
    command: "python app.py"
